name: Copy_Secrets

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo Name (e.g. MyRepo)'
        required: true
        default: ''
      org:
        description: 'Organization/User Name'
        required: false
        default: 'gendloop'
        type: choice
        options:
          - 'gendloop'
          - 'XiGeoAlgorithm'

jobs:
  copy_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: copy-secrets-to-org
        if: ${{ inputs.org == 'XiGeoAlgorithm' }}
        uses: gendloop/copy-secrets@v1.0.0
        with: 
          repo: ${{ inputs.repo }}
          repo_owner: ${{ inputs.org }}
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          secret_names: 'GENDLOOP_ACCESS_TOKEN'
          secret_values: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}

      - name: copy-secrets-to-person
        if: ${{ inputs.org == 'gendloop' }}
        uses: gendloop/copy-secrets@v1.0.0
        with: 
          repo: ${{ inputs.repo }}
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
          secret_names: 'GENDLOOP_ACCESS_TOKEN'
          secret_values: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}

      