name: Update_Submodules

permissions:
  contents: write
  actions: write

on: 
  workflow_dispatch:
  schedule:
    - cron: '35 16 * * 1,3,5'

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: update-submodules
        uses: gendloop/update-submodules@v1.0.0
        with: 
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}

      